version: '3'
# https://blog.csdn.net/u010900754/article/details/78588491
services:
  mysql_master:
    image: mysql:8.0.12
    container_name: mysql_master
    volumes:
      - ./master/:/etc/mysql/conf.d/
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    # ports:
    #   - "50001:3306"
 
  mysql_replica:
    image: mysql:8.0.12
    container_name: mysql_replica
    volumes:
      - ./replica/:/etc/mysql/conf.d/
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    # ports:
    #   - "50002:3306"
  
  mysql_configure:
    image: mysql:8.0.12
    container_name: mysql_configure
    environment:
      - "MYSQL_REPLICATION_PASSWORD=root"
      - "MYSQL_MASTER_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_REPLICATION_USER=repl"
      - "MYSQL_REPLICATION_PASSWORD=repl"
    volumes:
      - ./mysql_connector.sh:/tmp/mysql_connector.sh
    command: /bin/bash -x /tmp/mysql_connector.sh

