version: '3'
# https://blog.csdn.net/u010900754/article/details/78588491
services:
  mysqlmaster:
    image: mysql:8.0.12
    volumes:
      - ./master/:/etc/mysql/conf.d/
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    # ports:
    #   - "50001:3306"
 
  mysqlslave:
    image: mysql:8.0.12
    volumes:
      - ./replica/:/etc/mysql/conf.d/
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    # ports:
    #   - "50002:3306"
  
  mysqlconfigure:
    image: mysql:8.0.12
    environment:
      - "MYSQL_SLAVE_PASSWORD=root"
      - "MYSQL_MASTER_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_REPLICATION_USER=repl"
      - "MYSQL_REPLICATION_PASSWORD=repl"
    volumes:
      - ./mysql_connector.sh:/tmp/mysql_connector.sh
    command: /bin/bash -x /tmp/mysql_connector.sh

